services:
  - type: web
    name: gpt2-telegram-bot
    env: docker  # ✅ Use Docker instead of 'python'
    dockerfilePath: ./Dockerfile  # ✅ Tell Render to use your Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: STABILITY_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

